name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: feenkcom/feenkGitHubWorkflows/.github/workflows/checkForContributorLicenseAgreementSignature.yml@main
